### ISSUE TITLE
ATLAS review - Reference regions

### ISSUE THREAD

**Issue by huard** [IPCC-WG1/Atlas#17]
- [x] `IPCC-WGI-reference-regions-v4_coordinates.csv` : add header with column titles
- [ ] shapefiles could be distributed in geopackage format, an open standards-based format, instead of a proprietary format (https://www.geopackage.org/)
- [x] README: No explanation of what the Pacific small islands regions are for.

**Comment by jesusff** [comment]
Thank you for your review. Headers have been added to the reference regions CSV file. Also, it is now correctly rendered in github, so regions can be easily found using the search field. The small islands and other sets of regions have been described in the new readme in this folder.

Regarding the proprietary shapefile format, we keep it because it has a extended user base and it is supported by most GIS software. Thus, it enhances interoperabity. We added, though, the geojson format as an open alternative.
