### ISSUE TITLE
ATLAS review - notebooks

### ISSUE THREAD

**Issue by huard** [IPCC-WG1/Atlas#22]
I would like to find all the notebooks in the same place. Maybe use symlinks if you want to keep the original source in separate directories ? Notebooks include a lot of warnings and white space around figures which distract from the content.

**Comment by hot007** [comment]
Agree, I'm not sure about the point of having a 'notebooks' area that contains only one notebook, while there are notebooks in other places, presumably they should be consolidated to this folder.

**Comment by jesusff** [comment]
Thank you for the review. There is now a new directory structure (f494de8) which, hopefully, clarifies the purpose of top-level and inner notebooks/scripts (see main README). Other issue (#33) suggested to keep the structure, in order to facilitate access to relevant code for the different directories.

The idea in the new structure is to keep the notebooks/scripts that exemplify the use/creation of a particular resource (e.g. reference regions) under the directory of that resource. The top-level `notebooks` directory is intended for cross-cutting notebooks making a combined use of different resources in the repository. The top-level `scripts` directory has been renamed `reproducibility` to stress the idea of providing code that reproduces the key figures included in the AR6 Atlas chapter.

We will include additional notebook/script examples in the top-level directories in the following weeks, to better populate these directories.

**Comment by jesusff** [comment]
All notebooks have finally been moved to the top-level notebooks/ folder following this suggestion, and the number of available notebooks has been enlarged.
