### ISSUE TITLE
ATLAS Review - Comments and suggestions 

### ISSUE THREAD

**Issue by dimitrisTC** [IPCC-WG1/Atlas#35]
Thank you for the invitation to review the IPCC AR6 WGI Atlas. I believe this effort is fantastic, and I am sure it will improve the accessibility and understanding of the projected changes due to anthropogenic climate change. My comments and suggestions are to, what I consider, an improvement in the FAIR data practices. My overall suggestions are:

**1. ATLAS vs. Atlas.** I consider that we should be consistent and use one of those options. I would choose "Atlas" because, at first sight, "ATLAS" seems to be an acronym. 
**2. Include Python in addition to R (?)**. Despite the popularity of R, I believe that including Python could improve the accessibility and reproducibility of the Atlas. We could, for example, wrappers to run the R-based scripts in Python. At least in my institution, many users do not have experience using R but with Python.
**3. Model Validation.** I consider that it would be great to include observational climate data in addition to model data so that users can compare and validate, for example, trends in precipitation during the observed historical period (e.g., 1850-2015) its simulated counterpart. These comparisons are critical for assessments of anthropogenic climate change uncertainties at regional scales.
**4. Accessing the Atlas online.** For some reason, the links provided to access the Atlas (e.g., http://ipcc-atlas.ifca.es​ and ipcc-atlas.ifca.es/about) do not work.

**Comment by jesusff** [comment]
Thank you for your review. We followed your recommendation (and #31) and consistently used the wording Atlas, instead of ATLAS. We also included observational data in the same format as the rest of the model products (please, see #34). Regarding the URL to access the Interactive Atlas, it must have been some temporary failure, since they are currently redirecting correctly.

Regarding Python or other languages, we agree that this would increase FAIRness. There are very few sample notebooks in the repository using Python, but we encourage the community to contribute equivalent or additional notebooks exploring the data.
