### ISSUE TITLE
ATLAS Review - Comments

### ISSUE THREAD

**Issue by AlKhourdajie** [IPCC-WG1/Atlas#36]
Thank you very much for the fantistic effort putting the Atlas together. Here are some comments/question:
-	Can you specify the running requirements for R? version, platform, Jupyter, Anaconda? Etc. 
-	I think the scripts read well with comments. Can you include further background info in the README? Such as key papers. This would’ve been particularly useful for Git Warming Levels.
-	Is it possible to produce R-based scripts for Python?
-	Can you provide data DOIs?
Again, thank you very much for the effort putting this together. 
Best, 
Alaa

**Comment by jesusff** [comment]
Thank you for your review. The requirements to run the scripts and notebooks are now included in the main README (https://github.com/IPCC-WG1/Atlas#requirements). All READMEs have been extended and also the notebook details where references can also be found. Regarding Python, unfortunately, only a couple of notebooks are currently available. The main effort was on having a consistent set of notebooks providing an overview of the available products, rather than having them translated to different programming languages. This task is left for future collaboration from the community.
Regarding data DOIs, they do not refer to the variables, which are the basic pieces of the inventory. Thus, we opted for handles were available and ESGF search URLs pointing the corresponding variable dataset (see e.g. https://github.com/IPCC-WG1/Atlas/tree/151e4f08f245ebcfaff3975b2395a07ea539617d/inventory/CMIP6)
