### ISSUE TITLE
Mousing over Time Series Poorly Communicates Information

### ISSUE THREAD

**Issue by RylanSchaeffer** [IPCC-WG1/Atlas#48]
When you mouse over the time series, a small window appears which shows the year (the x value). From a communication perspective, the pop up should show the y value because (1) the y value is important, and (2) the y value is squished, so I can't see what the y-value is, whereas the x value (the year) is easily readable.

![image](https://user-images.githubusercontent.com/8942987/129463421-67488751-bd83-4bae-a136-03844f87583a.png)

**Comment by jesusff** [comment]
Thank you for your feedback. The lack of values for particular years is by design, since this information would be misleading. Only means over long periods, overall trends, or variability is meaningful. These can be assessed by hovering over the ensemble, when a particular model is highlighted and shown in the tooltip:  

![image](https://user-images.githubusercontent.com/8810015/134650725-f48818c3-8465-4ef9-869a-8bbf7acadbb0.png)

This also illustrates the transient behaviour of individual models within the ensemble.
